### health
GET {{host}}/

> {%
    client.test("Response", function () {
        client.assert(response.status === 200, "status");
        client.assert(response.body === "alive", "body");
    });
%}
